export enum MESSAGE_CODE {
  // Common
  DEFAULT_SUCCESS = 'DEFAULT_SUCCESS',
  DEFAULT_ERROR = 'DEFAULT_ERROR',
  NOT_FOUND_DATA = 'NOT_FOUND_DATA',

  // Success
  SUCCESS_CREATE_GAME = 'SUCCESS_CREATE_GAME',
  SUCCESS_UPDATE_GAME = 'SUCCESS_UPDATE_GAME',
  SUCCESS_LIST_GAME = 'SUCCESS_LIST_GAME',
  SUCCESS_DETAIL_GAME = 'SUCCESS_DETAIL_GAME',

  SUCCESS_UPDATE_ROLE = 'SUCCESS_UPDATE_ROLE',
  SUCCESS_DELETE_ROLE = 'SUCCESS_DELETE_ROLE',
  SUCCESS_LIST_ROLE = 'SUCCESS_LIST_ROLE',
  SUCCESS_DETAIL_ROLE = 'SUCCESS_DETAIL_ROLE',

  SUCCESS_CREATE_GAME_VERSION = 'SUCCESS_CREATE_GAME_VERSION',
  SUCCESS_UPDATE_GAME_VERSION = 'SUCCESS_UPDATE_GAME_VERSION',
  SUCCESS_DELETE_GAME_VERSION = 'SUCCESS_DELETE_GAME_VERSION',
  SUCCESS_LIST_GAME_VERSION = 'SUCCESS_LIST_GAME_VERSION',
  SUCCESS_DETAIL_GAME_VERSION = 'SUCCESS_DETAIL_GAME_VERSION',
  SUCCESS_DOWNLOAD_GAME_VERSION = 'SUCCESS_DOWNLOAD_GAME_VERSION',

  SUCCESS_CREATE_SUBMISSION = 'SUCCESS_CREATE_SUBMISSION',
  SUCCESS_UPDATE_SUBMISSION = 'SUCCESS_UPDATE_SUBMISSION',
  SUCCESS_LIST_SUBMISSION = 'SUCCESS_LIST_SUBMISSION',

  // Error
  ERROR_NOT_FOUND_DATA = 'ERROR_NOT_FOUND_DATA',
  ERROR_NOT_FOUND_FILE = 'ERROR_NOT_FOUND_FILE',
  ERROR_NOT_ALLOW_FILE_GAME_STRUCTURE = 'ERROR_NOT_ALLOW_FILE_GAME_STRUCTURE',
  ERROR_NOT_FOUND_USER = 'ERROR_NOT_FOUND_USER',
  ERROR_NOT_ALLOW = 'ERROR_NOT_ALLOW',

  ERROR_NOT_FOUND_GAME = 'ERROR_NOT_FOUND_GAME',
  ERROR_CREATE_GAME = 'ERROR_CREATE_GAME',
  ERROR_UPDATE_GAME = 'ERROR_UPDATE_GAME',
  ERROR_LIST_GAME = 'ERROR_LIST_GAME',
  ERROR_DETAIL_GAME = 'ERROR_DETAIL_GAME',

  ERROR_NOT_FOUND_GAME_VERSION = 'ERROR_NOT_FOUND_GAME_VERSION',
  ERROR_CREATE_GAME_VERSION = 'ERROR_CREATE_GAME_VERSION',
  ERROR_UPDATE_GAME_VERSION = 'ERROR_UPDATE_GAME_VERSION',
  ERROR_DELETE_GAME_VERSION = 'ERROR_DELETE_GAME_VERSION',
  ERROR_LIST_GAME_VERSION = 'ERROR_LIST_GAME_VERSION',
  ERROR_DETAIL_GAME_VERSION = 'ERROR_DETAIL_GAME_VERSION',
  ERROR_DOWNLOAD_GAME_VERSION = 'ERROR_DOWNLOAD_GAME_VERSION',

  ERROR_NOT_FOUND_ROLE = 'ERROR_NOT_FOUND_ROLE',
  ERROR_UPDATE_ROLE = 'ERROR_UPDATE_ROLE',
  ERROR_DELETE_ROLE = 'ERROR_DELETE_ROLE',
  ERROR_LIST_ROLE = 'ERROR_LIST_ROLE',
  ERROR_DETAIL_ROLE = 'ERROR_DETAIL_ROLE',

  ERROR_CREATE_SUBMISSION = 'ERROR_CREATE_SUBMISSION',
  ERROR_GAME_VERSION_NOT_VALID = 'ERROR_GAME_VERSION_NOT_VALID',
  ERROR_CHOOSE_THE_HIGHER_VERSION = 'ERROR_CHOOSE_THE_HIGHER_VERSION',
  ERROR_SUBMISSION_IS_BEING_APPROVED = 'ERROR_SUBMISSION_IS_BEING_APPROVED',
  ERROR_SUBMISSION_IS_APPROVED = 'ERROR_SUBMISSION_IS_APPROVED',
  ERROR_UPDATE_SUBMISSION = 'ERROR_UPDATE_SUBMISSION',
  ERROR_NOT_FOUND_SUBMISSION = 'ERROR_NOT_FOUND_SUBMISSION',
  ERROR_LIST_SUBMISSION = 'ERROR_LIST_SUBMISSION',
}

export enum MESSAGE_VALIDATION {
  ERROR_GAME_VERSION_WRONG_FORMAT = 'ERROR_GAME_VERSION_WRONG_FORMAT',
}
